[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npx prisma generate"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
